// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqoinmpydvgyzwkkrjdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxb2lubXB5ZHZneXp3a2tyamRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzODI3OTUsImV4cCI6MjA1Mzk1ODc5NX0.h6n8hemegH5ucbrduKWursyiWoELY_4jaIxma4FCd08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);